name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the feature1 branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the feature1 branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from GitHub repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # You can change this based on the version you're using

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build the React app
    - name: Build the React app
      run: npm run build

    # Step 5: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t my-react-app .

    # Step 6: Log in to Docker Hub (or your Docker registry)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: naveenprasaath29@gmail.com
        password: QAZwsc1729/*-+

    # Step 7: Push the Docker image
    - name: Push Docker image
      run: |
        docker tag my-react-app ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
